### PR TITLE
Add info dialog & login/logout for provider

### PR DESCRIPTION
**Pull request by OleksandrSPV**
https://github.com/user-attachments/assets/41a8a2fa-276d-45b7-b090-c166284c238f

https://github.com/user-attachments/assets/d1f710bc-9505-407c-b911-699abf5ca193

### CODE REVIEW

**Comment by OleksandrSPV** [comment]
@OlhaPeculiar Could you check please on https://fortify-tools.vercel.app Thanks.

**Comment by OlhaPeculiar** [comment]
Checked how YubiKey works, display, login, logout and changes in the number of certificates. Everything works correctly

**Review by donskov — DISMISSED** [review]

**Comment by OleksandrSPV** [comment]
@OlhaPeculiar Could you check please again. Thanks!

**Comment by OlhaPeculiar** [comment]
Checked: Everything works correctly

**Comment by OleksandrSPV** [comment]
@donskov Could you please merge it.

**Review by donskov — APPROVED** [review]

**Pull request merged**
