### PR TITLE
Version 2: Add stylistic Eslint

### PR DESCRIPTION
**Pull request by OleksandrSPV**
Eslint deprecated formatting rules in version 9 https://eslint.org/blog/2023/10/deprecating-formatting-rules/. So lets use additional package for this https://eslint.style/guide/getting-started

### CODE REVIEW

**Comment by OleksandrSPV** [comment]
@donskov We can add https://github.com/antfu/eslint-plugin-import-x too in this PR. Or will add this later in separate PR because there will be to many changes. What do you think?

**Comment by OleksandrSPV** [comment]
> @donskov We can add https://github.com/antfu/eslint-plugin-import-x in this PR too. Or will add this later in separate PR because there will be to many changes. What do you think?
Actually not much.
image
Should I add this?

**Comment by donskov** [comment]
@OleksandrSPV Could you please add a description to the PR about what we actually do and any reason to use the `-alpha` version of npm package?

**Comment by OleksandrSPV** [comment]
> @OleksandrSPV Could you please add a description to the PR about what we actually do and any reason to use the `-alpha` version of npm package?

Description added.

There are many collisions between plugins packages at the current transition period (Eslint from version 8 to 9), so I decided to use the alpha version of this package to avoid them. I tested it a lot, including on another project, everything works well.

@donskov

**Comment by donskov** [comment]
@OleksandrSPV If we have already started using one spelling check method, then we should use it and not mix it with others. Let's use [stylistic](https://eslint.style/packages/default) by default.

**Comment by OleksandrSPV** [comment]
> @OleksandrSPV If we have already started using one spelling check method, then we should use it and not mix it with others. Let's use [stylistic](https://eslint.style/packages/default) by default.

I don't understand what kind of mixing you're talking about, sorry. Could you please clarify? @donskov

**Comment by OleksandrSPV** [comment]
> > > @OleksandrSPV If we have already started using one spelling check method, then we should use it and not mix it with others. Let's use [stylistic](https://eslint.style/packages/default) by default.
> > 
> > 
> > I don't understand what kind of mixing you're talking about, sorry. Could you please clarify? @donskov
> 
> I see that the `@stylistic/eslint-plugin` includes rules for React/Typescript/JS. Just curious, why do we need other dependencies if we can use only this one?

Ok, let me think to optimise it.

**Comment by OleksandrSPV** [comment]
> `-alpha` version of npm package

The typescript-eslint v.8 package was released, so there is no -alpha version of npm package now. I updated it.
@donskov

**Comment by OleksandrSPV** [comment]
I decided to take another way

**Pull request closed without merging**
